packages:
  - app
  - "packages/*"

allowBuilds:
  '@alicloud/openapi-core': false
  es5-ext: true
  esbuild: true

minimumReleaseAgeExclude:
  - '@tanstack/ai@0.52.2'
  - '@easyx/editor@1.1.1 || 1.1.2 || 2.0.0'
  - '@easyx/ai-rich-editor@0.1.0 || 2.0.0'
  - '@easyx/image-toolkit@0.1.0 || 1.0.0'
  - '@easyx/tiptap-table-plus@1.0.1'

onlyBuiltDependencies:
  - esbuild
  - lightningcss
