packages:
  - app
  - "packages/*"

allowBuilds:
  '@alicloud/openapi-core': false
  es5-ext: true
  esbuild: true

minimumReleaseAgeExclude:
  - '@tanstack/ai@0.52.2'

onlyBuiltDependencies:
  - esbuild
  - lightningcss
