/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AdminLoginIndexRouteImport } from './routes/admin/login/index'
import { Route as AdminInitIndexRouteImport } from './routes/admin/init/index'
import { Route as AdminForgotPasswordIndexRouteImport } from './routes/admin/forgot-password/index'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as AdminAdminOperationLogsIndexRouteImport } from './routes/admin/_admin/operation-logs/index'
import { Route as AdminAdminNewsIndexRouteImport } from './routes/admin/_admin/news/index'
import { Route as AdminAdminMessagesIndexRouteImport } from './routes/admin/_admin/messages/index'
import { Route as AdminAdminLogsIndexRouteImport } from './routes/admin/_admin/logs/index'
import { Route as AdminAdminFilesIndexRouteImport } from './routes/admin/_admin/files/index'
import { Route as AdminAdminFileExplorerIndexRouteImport } from './routes/admin/_admin/file-explorer/index'
import { Route as AdminAdminDictsIndexRouteImport } from './routes/admin/_admin/dicts/index'
import { Route as AdminAdminConfigIndexRouteImport } from './routes/admin/_admin/config/index'
import { Route as AdminAdminAdminRolesIndexRouteImport } from './routes/admin/_admin/admin-roles/index'
import { Route as ApiDownloadLogIdRouteImport } from './routes/api/download/log.$id'
import { Route as ApiDownloadFileIdRouteImport } from './routes/api/download/file.$id'
import { Route as ApiDownloadFileExplorerSplatRouteImport } from './routes/api/download/file-explorer/$'
import { Route as AdminAdminTranslationsUiRouteImport } from './routes/admin/_admin/translations/ui'
import { Route as AdminAdminTranslationsContentRouteImport } from './routes/admin/_admin/translations/content'
import { Route as AdminAdminTrackQueryRouteImport } from './routes/admin/_admin/track/query'
import { Route as AdminAdminTrackAnalyticsRouteImport } from './routes/admin/_admin/track/analytics'
import { Route as AdminAdminNewsCreateRouteImport } from './routes/admin/_admin/news/create'
import { Route as AdminAdminMessagesManageRouteImport } from './routes/admin/_admin/messages/manage'
import { Route as AdminAdminDemoUploadRouteImport } from './routes/admin/_admin/demo/upload'
import { Route as AdminAdminDemoProTableRouteImport } from './routes/admin/_admin/demo/pro-table'
import { Route as AdminAdminDemoEditorRouteImport } from './routes/admin/_admin/demo/editor'
import { Route as AdminAdminDemoAiRouteImport } from './routes/admin/_admin/demo/ai'
import { Route as AdminAdminUsersClientsIndexRouteImport } from './routes/admin/_admin/users/clients/index'
import { Route as AdminAdminUsersAdminsIndexRouteImport } from './routes/admin/_admin/users/admins/index'
import { Route as AdminAdminTrackPropertyMetaIndexRouteImport } from './routes/admin/_admin/track/property-meta/index'
import { Route as AdminAdminTrackEventMetaIndexRouteImport } from './routes/admin/_admin/track/event-meta/index'
import { Route as AdminAdminNewsIdEditRouteImport } from './routes/admin/_admin/news/$id/edit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInitIndexRoute = AdminInitIndexRouteImport.update({
  id: '/init/',
  path: '/init/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordIndexRoute =
  AdminForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOperationLogsIndexRoute =
  AdminAdminOperationLogsIndexRouteImport.update({
    id: '/operation-logs/',
    path: '/operation-logs/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminNewsIndexRoute = AdminAdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMessagesIndexRoute = AdminAdminMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLogsIndexRoute = AdminAdminLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFilesIndexRoute = AdminAdminFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFileExplorerIndexRoute =
  AdminAdminFileExplorerIndexRouteImport.update({
    id: '/file-explorer/',
    path: '/file-explorer/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminDictsIndexRoute = AdminAdminDictsIndexRouteImport.update({
  id: '/dicts/',
  path: '/dicts/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminConfigIndexRoute = AdminAdminConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAdminRolesIndexRoute =
  AdminAdminAdminRolesIndexRouteImport.update({
    id: '/admin-roles/',
    path: '/admin-roles/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const ApiDownloadLogIdRoute = ApiDownloadLogIdRouteImport.update({
  id: '/api/download/log/$id',
  path: '/api/download/log/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadFileIdRoute = ApiDownloadFileIdRouteImport.update({
  id: '/api/download/file/$id',
  path: '/api/download/file/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadFileExplorerSplatRoute =
  ApiDownloadFileExplorerSplatRouteImport.update({
    id: '/api/download/file-explorer/$',
    path: '/api/download/file-explorer/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdminTranslationsUiRoute =
  AdminAdminTranslationsUiRouteImport.update({
    id: '/translations/ui',
    path: '/translations/ui',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminTranslationsContentRoute =
  AdminAdminTranslationsContentRouteImport.update({
    id: '/translations/content',
    path: '/translations/content',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminTrackQueryRoute = AdminAdminTrackQueryRouteImport.update({
  id: '/track/query',
  path: '/track/query',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTrackAnalyticsRoute =
  AdminAdminTrackAnalyticsRouteImport.update({
    id: '/track/analytics',
    path: '/track/analytics',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminNewsCreateRoute = AdminAdminNewsCreateRouteImport.update({
  id: '/news/create',
  path: '/news/create',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMessagesManageRoute =
  AdminAdminMessagesManageRouteImport.update({
    id: '/messages/manage',
    path: '/messages/manage',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminDemoUploadRoute = AdminAdminDemoUploadRouteImport.update({
  id: '/demo/upload',
  path: '/demo/upload',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDemoProTableRoute = AdminAdminDemoProTableRouteImport.update({
  id: '/demo/pro-table',
  path: '/demo/pro-table',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDemoEditorRoute = AdminAdminDemoEditorRouteImport.update({
  id: '/demo/editor',
  path: '/demo/editor',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDemoAiRoute = AdminAdminDemoAiRouteImport.update({
  id: '/demo/ai',
  path: '/demo/ai',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersClientsIndexRoute =
  AdminAdminUsersClientsIndexRouteImport.update({
    id: '/users/clients/',
    path: '/users/clients/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminUsersAdminsIndexRoute =
  AdminAdminUsersAdminsIndexRouteImport.update({
    id: '/users/admins/',
    path: '/users/admins/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminTrackPropertyMetaIndexRoute =
  AdminAdminTrackPropertyMetaIndexRouteImport.update({
    id: '/track/property-meta/',
    path: '/track/property-meta/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminTrackEventMetaIndexRoute =
  AdminAdminTrackEventMetaIndexRouteImport.update({
    id: '/track/event-meta/',
    path: '/track/event-meta/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminNewsIdEditRoute = AdminAdminNewsIdEditRouteImport.update({
  id: '/news/$id/edit',
  path: '/news/$id/edit',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/forgot-password/': typeof AdminForgotPasswordIndexRoute
  '/admin/init/': typeof AdminInitIndexRoute
  '/admin/login/': typeof AdminLoginIndexRoute
  '/admin/demo/ai': typeof AdminAdminDemoAiRoute
  '/admin/demo/editor': typeof AdminAdminDemoEditorRoute
  '/admin/demo/pro-table': typeof AdminAdminDemoProTableRoute
  '/admin/demo/upload': typeof AdminAdminDemoUploadRoute
  '/admin/messages/manage': typeof AdminAdminMessagesManageRoute
  '/admin/news/create': typeof AdminAdminNewsCreateRoute
  '/admin/track/analytics': typeof AdminAdminTrackAnalyticsRoute
  '/admin/track/query': typeof AdminAdminTrackQueryRoute
  '/admin/translations/content': typeof AdminAdminTranslationsContentRoute
  '/admin/translations/ui': typeof AdminAdminTranslationsUiRoute
  '/api/download/file-explorer/$': typeof ApiDownloadFileExplorerSplatRoute
  '/api/download/file/$id': typeof ApiDownloadFileIdRoute
  '/api/download/log/$id': typeof ApiDownloadLogIdRoute
  '/admin/admin-roles/': typeof AdminAdminAdminRolesIndexRoute
  '/admin/config/': typeof AdminAdminConfigIndexRoute
  '/admin/dicts/': typeof AdminAdminDictsIndexRoute
  '/admin/file-explorer/': typeof AdminAdminFileExplorerIndexRoute
  '/admin/files/': typeof AdminAdminFilesIndexRoute
  '/admin/logs/': typeof AdminAdminLogsIndexRoute
  '/admin/messages/': typeof AdminAdminMessagesIndexRoute
  '/admin/news/': typeof AdminAdminNewsIndexRoute
  '/admin/operation-logs/': typeof AdminAdminOperationLogsIndexRoute
  '/admin/news/$id/edit': typeof AdminAdminNewsIdEditRoute
  '/admin/track/event-meta/': typeof AdminAdminTrackEventMetaIndexRoute
  '/admin/track/property-meta/': typeof AdminAdminTrackPropertyMetaIndexRoute
  '/admin/users/admins/': typeof AdminAdminUsersAdminsIndexRoute
  '/admin/users/clients/': typeof AdminAdminUsersClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminAdminIndexRoute
  '/news/$slug': typeof NewsSlugRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/news': typeof NewsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/admin/forgot-password': typeof AdminForgotPasswordIndexRoute
  '/admin/init': typeof AdminInitIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/admin/demo/ai': typeof AdminAdminDemoAiRoute
  '/admin/demo/editor': typeof AdminAdminDemoEditorRoute
  '/admin/demo/pro-table': typeof AdminAdminDemoProTableRoute
  '/admin/demo/upload': typeof AdminAdminDemoUploadRoute
  '/admin/messages/manage': typeof AdminAdminMessagesManageRoute
  '/admin/news/create': typeof AdminAdminNewsCreateRoute
  '/admin/track/analytics': typeof AdminAdminTrackAnalyticsRoute
  '/admin/track/query': typeof AdminAdminTrackQueryRoute
  '/admin/translations/content': typeof AdminAdminTranslationsContentRoute
  '/admin/translations/ui': typeof AdminAdminTranslationsUiRoute
  '/api/download/file-explorer/$': typeof ApiDownloadFileExplorerSplatRoute
  '/api/download/file/$id': typeof ApiDownloadFileIdRoute
  '/api/download/log/$id': typeof ApiDownloadLogIdRoute
  '/admin/admin-roles': typeof AdminAdminAdminRolesIndexRoute
  '/admin/config': typeof AdminAdminConfigIndexRoute
  '/admin/dicts': typeof AdminAdminDictsIndexRoute
  '/admin/file-explorer': typeof AdminAdminFileExplorerIndexRoute
  '/admin/files': typeof AdminAdminFilesIndexRoute
  '/admin/logs': typeof AdminAdminLogsIndexRoute
  '/admin/messages': typeof AdminAdminMessagesIndexRoute
  '/admin/news': typeof AdminAdminNewsIndexRoute
  '/admin/operation-logs': typeof AdminAdminOperationLogsIndexRoute
  '/admin/news/$id/edit': typeof AdminAdminNewsIdEditRoute
  '/admin/track/event-meta': typeof AdminAdminTrackEventMetaIndexRoute
  '/admin/track/property-meta': typeof AdminAdminTrackPropertyMetaIndexRoute
  '/admin/users/admins': typeof AdminAdminUsersAdminsIndexRoute
  '/admin/users/clients': typeof AdminAdminUsersClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/admin/forgot-password/': typeof AdminForgotPasswordIndexRoute
  '/admin/init/': typeof AdminInitIndexRoute
  '/admin/login/': typeof AdminLoginIndexRoute
  '/admin/_admin/demo/ai': typeof AdminAdminDemoAiRoute
  '/admin/_admin/demo/editor': typeof AdminAdminDemoEditorRoute
  '/admin/_admin/demo/pro-table': typeof AdminAdminDemoProTableRoute
  '/admin/_admin/demo/upload': typeof AdminAdminDemoUploadRoute
  '/admin/_admin/messages/manage': typeof AdminAdminMessagesManageRoute
  '/admin/_admin/news/create': typeof AdminAdminNewsCreateRoute
  '/admin/_admin/track/analytics': typeof AdminAdminTrackAnalyticsRoute
  '/admin/_admin/track/query': typeof AdminAdminTrackQueryRoute
  '/admin/_admin/translations/content': typeof AdminAdminTranslationsContentRoute
  '/admin/_admin/translations/ui': typeof AdminAdminTranslationsUiRoute
  '/api/download/file-explorer/$': typeof ApiDownloadFileExplorerSplatRoute
  '/api/download/file/$id': typeof ApiDownloadFileIdRoute
  '/api/download/log/$id': typeof ApiDownloadLogIdRoute
  '/admin/_admin/admin-roles/': typeof AdminAdminAdminRolesIndexRoute
  '/admin/_admin/config/': typeof AdminAdminConfigIndexRoute
  '/admin/_admin/dicts/': typeof AdminAdminDictsIndexRoute
  '/admin/_admin/file-explorer/': typeof AdminAdminFileExplorerIndexRoute
  '/admin/_admin/files/': typeof AdminAdminFilesIndexRoute
  '/admin/_admin/logs/': typeof AdminAdminLogsIndexRoute
  '/admin/_admin/messages/': typeof AdminAdminMessagesIndexRoute
  '/admin/_admin/news/': typeof AdminAdminNewsIndexRoute
  '/admin/_admin/operation-logs/': typeof AdminAdminOperationLogsIndexRoute
  '/admin/_admin/news/$id/edit': typeof AdminAdminNewsIdEditRoute
  '/admin/_admin/track/event-meta/': typeof AdminAdminTrackEventMetaIndexRoute
  '/admin/_admin/track/property-meta/': typeof AdminAdminTrackPropertyMetaIndexRoute
  '/admin/_admin/users/admins/': typeof AdminAdminUsersAdminsIndexRoute
  '/admin/_admin/users/clients/': typeof AdminAdminUsersClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/news/$slug'
    | '/forgot-password/'
    | '/login/'
    | '/messages/'
    | '/news/'
    | '/register/'
    | '/admin/'
    | '/admin/forgot-password/'
    | '/admin/init/'
    | '/admin/login/'
    | '/admin/demo/ai'
    | '/admin/demo/editor'
    | '/admin/demo/pro-table'
    | '/admin/demo/upload'
    | '/admin/messages/manage'
    | '/admin/news/create'
    | '/admin/track/analytics'
    | '/admin/track/query'
    | '/admin/translations/content'
    | '/admin/translations/ui'
    | '/api/download/file-explorer/$'
    | '/api/download/file/$id'
    | '/api/download/log/$id'
    | '/admin/admin-roles/'
    | '/admin/config/'
    | '/admin/dicts/'
    | '/admin/file-explorer/'
    | '/admin/files/'
    | '/admin/logs/'
    | '/admin/messages/'
    | '/admin/news/'
    | '/admin/operation-logs/'
    | '/admin/news/$id/edit'
    | '/admin/track/event-meta/'
    | '/admin/track/property-meta/'
    | '/admin/users/admins/'
    | '/admin/users/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/news/$slug'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/news'
    | '/register'
    | '/admin/forgot-password'
    | '/admin/init'
    | '/admin/login'
    | '/admin/demo/ai'
    | '/admin/demo/editor'
    | '/admin/demo/pro-table'
    | '/admin/demo/upload'
    | '/admin/messages/manage'
    | '/admin/news/create'
    | '/admin/track/analytics'
    | '/admin/track/query'
    | '/admin/translations/content'
    | '/admin/translations/ui'
    | '/api/download/file-explorer/$'
    | '/api/download/file/$id'
    | '/api/download/log/$id'
    | '/admin/admin-roles'
    | '/admin/config'
    | '/admin/dicts'
    | '/admin/file-explorer'
    | '/admin/files'
    | '/admin/logs'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/operation-logs'
    | '/admin/news/$id/edit'
    | '/admin/track/event-meta'
    | '/admin/track/property-meta'
    | '/admin/users/admins'
    | '/admin/users/clients'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin/_admin'
    | '/news/$slug'
    | '/forgot-password/'
    | '/login/'
    | '/messages/'
    | '/news/'
    | '/register/'
    | '/admin/_admin/'
    | '/admin/forgot-password/'
    | '/admin/init/'
    | '/admin/login/'
    | '/admin/_admin/demo/ai'
    | '/admin/_admin/demo/editor'
    | '/admin/_admin/demo/pro-table'
    | '/admin/_admin/demo/upload'
    | '/admin/_admin/messages/manage'
    | '/admin/_admin/news/create'
    | '/admin/_admin/track/analytics'
    | '/admin/_admin/track/query'
    | '/admin/_admin/translations/content'
    | '/admin/_admin/translations/ui'
    | '/api/download/file-explorer/$'
    | '/api/download/file/$id'
    | '/api/download/log/$id'
    | '/admin/_admin/admin-roles/'
    | '/admin/_admin/config/'
    | '/admin/_admin/dicts/'
    | '/admin/_admin/file-explorer/'
    | '/admin/_admin/files/'
    | '/admin/_admin/logs/'
    | '/admin/_admin/messages/'
    | '/admin/_admin/news/'
    | '/admin/_admin/operation-logs/'
    | '/admin/_admin/news/$id/edit'
    | '/admin/_admin/track/event-meta/'
    | '/admin/_admin/track/property-meta/'
    | '/admin/_admin/users/admins/'
    | '/admin/_admin/users/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  NewsSlugRoute: typeof NewsSlugRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ApiDownloadFileExplorerSplatRoute: typeof ApiDownloadFileExplorerSplatRoute
  ApiDownloadFileIdRoute: typeof ApiDownloadFileIdRoute
  ApiDownloadLogIdRoute: typeof ApiDownloadLogIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login/': {
      id: '/admin/login/'
      path: '/login'
      fullPath: '/admin/login/'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/init/': {
      id: '/admin/init/'
      path: '/init'
      fullPath: '/admin/init/'
      preLoaderRoute: typeof AdminInitIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password/': {
      id: '/admin/forgot-password/'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password/'
      preLoaderRoute: typeof AdminForgotPasswordIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/operation-logs/': {
      id: '/admin/_admin/operation-logs/'
      path: '/operation-logs'
      fullPath: '/admin/operation-logs/'
      preLoaderRoute: typeof AdminAdminOperationLogsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/news/': {
      id: '/admin/_admin/news/'
      path: '/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminAdminNewsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/messages/': {
      id: '/admin/_admin/messages/'
      path: '/messages'
      fullPath: '/admin/messages/'
      preLoaderRoute: typeof AdminAdminMessagesIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/logs/': {
      id: '/admin/_admin/logs/'
      path: '/logs'
      fullPath: '/admin/logs/'
      preLoaderRoute: typeof AdminAdminLogsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/files/': {
      id: '/admin/_admin/files/'
      path: '/files'
      fullPath: '/admin/files/'
      preLoaderRoute: typeof AdminAdminFilesIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/file-explorer/': {
      id: '/admin/_admin/file-explorer/'
      path: '/file-explorer'
      fullPath: '/admin/file-explorer/'
      preLoaderRoute: typeof AdminAdminFileExplorerIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/dicts/': {
      id: '/admin/_admin/dicts/'
      path: '/dicts'
      fullPath: '/admin/dicts/'
      preLoaderRoute: typeof AdminAdminDictsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/config/': {
      id: '/admin/_admin/config/'
      path: '/config'
      fullPath: '/admin/config/'
      preLoaderRoute: typeof AdminAdminConfigIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/admin-roles/': {
      id: '/admin/_admin/admin-roles/'
      path: '/admin-roles'
      fullPath: '/admin/admin-roles/'
      preLoaderRoute: typeof AdminAdminAdminRolesIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/api/download/log/$id': {
      id: '/api/download/log/$id'
      path: '/api/download/log/$id'
      fullPath: '/api/download/log/$id'
      preLoaderRoute: typeof ApiDownloadLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/file/$id': {
      id: '/api/download/file/$id'
      path: '/api/download/file/$id'
      fullPath: '/api/download/file/$id'
      preLoaderRoute: typeof ApiDownloadFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/file-explorer/$': {
      id: '/api/download/file-explorer/$'
      path: '/api/download/file-explorer/$'
      fullPath: '/api/download/file-explorer/$'
      preLoaderRoute: typeof ApiDownloadFileExplorerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/translations/ui': {
      id: '/admin/_admin/translations/ui'
      path: '/translations/ui'
      fullPath: '/admin/translations/ui'
      preLoaderRoute: typeof AdminAdminTranslationsUiRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/translations/content': {
      id: '/admin/_admin/translations/content'
      path: '/translations/content'
      fullPath: '/admin/translations/content'
      preLoaderRoute: typeof AdminAdminTranslationsContentRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/track/query': {
      id: '/admin/_admin/track/query'
      path: '/track/query'
      fullPath: '/admin/track/query'
      preLoaderRoute: typeof AdminAdminTrackQueryRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/track/analytics': {
      id: '/admin/_admin/track/analytics'
      path: '/track/analytics'
      fullPath: '/admin/track/analytics'
      preLoaderRoute: typeof AdminAdminTrackAnalyticsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/news/create': {
      id: '/admin/_admin/news/create'
      path: '/news/create'
      fullPath: '/admin/news/create'
      preLoaderRoute: typeof AdminAdminNewsCreateRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/messages/manage': {
      id: '/admin/_admin/messages/manage'
      path: '/messages/manage'
      fullPath: '/admin/messages/manage'
      preLoaderRoute: typeof AdminAdminMessagesManageRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/demo/upload': {
      id: '/admin/_admin/demo/upload'
      path: '/demo/upload'
      fullPath: '/admin/demo/upload'
      preLoaderRoute: typeof AdminAdminDemoUploadRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/demo/pro-table': {
      id: '/admin/_admin/demo/pro-table'
      path: '/demo/pro-table'
      fullPath: '/admin/demo/pro-table'
      preLoaderRoute: typeof AdminAdminDemoProTableRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/demo/editor': {
      id: '/admin/_admin/demo/editor'
      path: '/demo/editor'
      fullPath: '/admin/demo/editor'
      preLoaderRoute: typeof AdminAdminDemoEditorRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/demo/ai': {
      id: '/admin/_admin/demo/ai'
      path: '/demo/ai'
      fullPath: '/admin/demo/ai'
      preLoaderRoute: typeof AdminAdminDemoAiRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/users/clients/': {
      id: '/admin/_admin/users/clients/'
      path: '/users/clients'
      fullPath: '/admin/users/clients/'
      preLoaderRoute: typeof AdminAdminUsersClientsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/users/admins/': {
      id: '/admin/_admin/users/admins/'
      path: '/users/admins'
      fullPath: '/admin/users/admins/'
      preLoaderRoute: typeof AdminAdminUsersAdminsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/track/property-meta/': {
      id: '/admin/_admin/track/property-meta/'
      path: '/track/property-meta'
      fullPath: '/admin/track/property-meta/'
      preLoaderRoute: typeof AdminAdminTrackPropertyMetaIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/track/event-meta/': {
      id: '/admin/_admin/track/event-meta/'
      path: '/track/event-meta'
      fullPath: '/admin/track/event-meta/'
      preLoaderRoute: typeof AdminAdminTrackEventMetaIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/news/$id/edit': {
      id: '/admin/_admin/news/$id/edit'
      path: '/news/$id/edit'
      fullPath: '/admin/news/$id/edit'
      preLoaderRoute: typeof AdminAdminNewsIdEditRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminDemoAiRoute: typeof AdminAdminDemoAiRoute
  AdminAdminDemoEditorRoute: typeof AdminAdminDemoEditorRoute
  AdminAdminDemoProTableRoute: typeof AdminAdminDemoProTableRoute
  AdminAdminDemoUploadRoute: typeof AdminAdminDemoUploadRoute
  AdminAdminMessagesManageRoute: typeof AdminAdminMessagesManageRoute
  AdminAdminNewsCreateRoute: typeof AdminAdminNewsCreateRoute
  AdminAdminTrackAnalyticsRoute: typeof AdminAdminTrackAnalyticsRoute
  AdminAdminTrackQueryRoute: typeof AdminAdminTrackQueryRoute
  AdminAdminTranslationsContentRoute: typeof AdminAdminTranslationsContentRoute
  AdminAdminTranslationsUiRoute: typeof AdminAdminTranslationsUiRoute
  AdminAdminAdminRolesIndexRoute: typeof AdminAdminAdminRolesIndexRoute
  AdminAdminConfigIndexRoute: typeof AdminAdminConfigIndexRoute
  AdminAdminDictsIndexRoute: typeof AdminAdminDictsIndexRoute
  AdminAdminFileExplorerIndexRoute: typeof AdminAdminFileExplorerIndexRoute
  AdminAdminFilesIndexRoute: typeof AdminAdminFilesIndexRoute
  AdminAdminLogsIndexRoute: typeof AdminAdminLogsIndexRoute
  AdminAdminMessagesIndexRoute: typeof AdminAdminMessagesIndexRoute
  AdminAdminNewsIndexRoute: typeof AdminAdminNewsIndexRoute
  AdminAdminOperationLogsIndexRoute: typeof AdminAdminOperationLogsIndexRoute
  AdminAdminNewsIdEditRoute: typeof AdminAdminNewsIdEditRoute
  AdminAdminTrackEventMetaIndexRoute: typeof AdminAdminTrackEventMetaIndexRoute
  AdminAdminTrackPropertyMetaIndexRoute: typeof AdminAdminTrackPropertyMetaIndexRoute
  AdminAdminUsersAdminsIndexRoute: typeof AdminAdminUsersAdminsIndexRoute
  AdminAdminUsersClientsIndexRoute: typeof AdminAdminUsersClientsIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminDemoAiRoute: AdminAdminDemoAiRoute,
  AdminAdminDemoEditorRoute: AdminAdminDemoEditorRoute,
  AdminAdminDemoProTableRoute: AdminAdminDemoProTableRoute,
  AdminAdminDemoUploadRoute: AdminAdminDemoUploadRoute,
  AdminAdminMessagesManageRoute: AdminAdminMessagesManageRoute,
  AdminAdminNewsCreateRoute: AdminAdminNewsCreateRoute,
  AdminAdminTrackAnalyticsRoute: AdminAdminTrackAnalyticsRoute,
  AdminAdminTrackQueryRoute: AdminAdminTrackQueryRoute,
  AdminAdminTranslationsContentRoute: AdminAdminTranslationsContentRoute,
  AdminAdminTranslationsUiRoute: AdminAdminTranslationsUiRoute,
  AdminAdminAdminRolesIndexRoute: AdminAdminAdminRolesIndexRoute,
  AdminAdminConfigIndexRoute: AdminAdminConfigIndexRoute,
  AdminAdminDictsIndexRoute: AdminAdminDictsIndexRoute,
  AdminAdminFileExplorerIndexRoute: AdminAdminFileExplorerIndexRoute,
  AdminAdminFilesIndexRoute: AdminAdminFilesIndexRoute,
  AdminAdminLogsIndexRoute: AdminAdminLogsIndexRoute,
  AdminAdminMessagesIndexRoute: AdminAdminMessagesIndexRoute,
  AdminAdminNewsIndexRoute: AdminAdminNewsIndexRoute,
  AdminAdminOperationLogsIndexRoute: AdminAdminOperationLogsIndexRoute,
  AdminAdminNewsIdEditRoute: AdminAdminNewsIdEditRoute,
  AdminAdminTrackEventMetaIndexRoute: AdminAdminTrackEventMetaIndexRoute,
  AdminAdminTrackPropertyMetaIndexRoute: AdminAdminTrackPropertyMetaIndexRoute,
  AdminAdminUsersAdminsIndexRoute: AdminAdminUsersAdminsIndexRoute,
  AdminAdminUsersClientsIndexRoute: AdminAdminUsersClientsIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AdminForgotPasswordIndexRoute: typeof AdminForgotPasswordIndexRoute
  AdminInitIndexRoute: typeof AdminInitIndexRoute
  AdminLoginIndexRoute: typeof AdminLoginIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AdminForgotPasswordIndexRoute: AdminForgotPasswordIndexRoute,
  AdminInitIndexRoute: AdminInitIndexRoute,
  AdminLoginIndexRoute: AdminLoginIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  NewsSlugRoute: NewsSlugRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ApiDownloadFileExplorerSplatRoute: ApiDownloadFileExplorerSplatRoute,
  ApiDownloadFileIdRoute: ApiDownloadFileIdRoute,
  ApiDownloadLogIdRoute: ApiDownloadLogIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
