/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInitRouteImport } from './routes/admin/init'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as AdminAdminRolesIndexRouteImport } from './routes/admin/_admin/roles/index'
import { Route as AdminAdminNewsIndexRouteImport } from './routes/admin/_admin/news/index'
import { Route as AdminAdminLogsIndexRouteImport } from './routes/admin/_admin/logs/index'
import { Route as AdminAdminFilesIndexRouteImport } from './routes/admin/_admin/files/index'
import { Route as AdminAdminDictsIndexRouteImport } from './routes/admin/_admin/dicts/index'
import { Route as AdminAdminConfigIndexRouteImport } from './routes/admin/_admin/config/index'
import { Route as AdminAdminNewsCreateRouteImport } from './routes/admin/_admin/news/create'
import { Route as AdminAdminUsersClientsIndexRouteImport } from './routes/admin/_admin/users/clients/index'
import { Route as AdminAdminUsersAdminsIndexRouteImport } from './routes/admin/_admin/users/admins/index'
import { Route as AdminAdminNewsIdEditRouteImport } from './routes/admin/_admin/news/$id/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInitRoute = AdminInitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRolesIndexRoute = AdminAdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminNewsIndexRoute = AdminAdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLogsIndexRoute = AdminAdminLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFilesIndexRoute = AdminAdminFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDictsIndexRoute = AdminAdminDictsIndexRouteImport.update({
  id: '/dicts/',
  path: '/dicts/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminConfigIndexRoute = AdminAdminConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminNewsCreateRoute = AdminAdminNewsCreateRouteImport.update({
  id: '/news/create',
  path: '/news/create',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersClientsIndexRoute =
  AdminAdminUsersClientsIndexRouteImport.update({
    id: '/users/clients/',
    path: '/users/clients/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminUsersAdminsIndexRoute =
  AdminAdminUsersAdminsIndexRouteImport.update({
    id: '/users/admins/',
    path: '/users/admins/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminNewsIdEditRoute = AdminAdminNewsIdEditRouteImport.update({
  id: '/news/$id/edit',
  path: '/news/$id/edit',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/init': typeof AdminInitRoute
  '/admin/login': typeof AdminLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/news/create': typeof AdminAdminNewsCreateRoute
  '/admin/config/': typeof AdminAdminConfigIndexRoute
  '/admin/dicts/': typeof AdminAdminDictsIndexRoute
  '/admin/files/': typeof AdminAdminFilesIndexRoute
  '/admin/logs/': typeof AdminAdminLogsIndexRoute
  '/admin/news/': typeof AdminAdminNewsIndexRoute
  '/admin/roles/': typeof AdminAdminRolesIndexRoute
  '/admin/news/$id/edit': typeof AdminAdminNewsIdEditRoute
  '/admin/users/admins/': typeof AdminAdminUsersAdminsIndexRoute
  '/admin/users/clients/': typeof AdminAdminUsersClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminAdminIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/init': typeof AdminInitRoute
  '/admin/login': typeof AdminLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news': typeof NewsIndexRoute
  '/admin/news/create': typeof AdminAdminNewsCreateRoute
  '/admin/config': typeof AdminAdminConfigIndexRoute
  '/admin/dicts': typeof AdminAdminDictsIndexRoute
  '/admin/files': typeof AdminAdminFilesIndexRoute
  '/admin/logs': typeof AdminAdminLogsIndexRoute
  '/admin/news': typeof AdminAdminNewsIndexRoute
  '/admin/roles': typeof AdminAdminRolesIndexRoute
  '/admin/news/$id/edit': typeof AdminAdminNewsIdEditRoute
  '/admin/users/admins': typeof AdminAdminUsersAdminsIndexRoute
  '/admin/users/clients': typeof AdminAdminUsersClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/admin/init': typeof AdminInitRoute
  '/admin/login': typeof AdminLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/admin/_admin/news/create': typeof AdminAdminNewsCreateRoute
  '/admin/_admin/config/': typeof AdminAdminConfigIndexRoute
  '/admin/_admin/dicts/': typeof AdminAdminDictsIndexRoute
  '/admin/_admin/files/': typeof AdminAdminFilesIndexRoute
  '/admin/_admin/logs/': typeof AdminAdminLogsIndexRoute
  '/admin/_admin/news/': typeof AdminAdminNewsIndexRoute
  '/admin/_admin/roles/': typeof AdminAdminRolesIndexRoute
  '/admin/_admin/news/$id/edit': typeof AdminAdminNewsIdEditRoute
  '/admin/_admin/users/admins/': typeof AdminAdminUsersAdminsIndexRoute
  '/admin/_admin/users/clients/': typeof AdminAdminUsersClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/init'
    | '/admin/login'
    | '/news/$slug'
    | '/news/'
    | '/admin/'
    | '/admin/news/create'
    | '/admin/config/'
    | '/admin/dicts/'
    | '/admin/files/'
    | '/admin/logs/'
    | '/admin/news/'
    | '/admin/roles/'
    | '/admin/news/$id/edit'
    | '/admin/users/admins/'
    | '/admin/users/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/init'
    | '/admin/login'
    | '/news/$slug'
    | '/news'
    | '/admin/news/create'
    | '/admin/config'
    | '/admin/dicts'
    | '/admin/files'
    | '/admin/logs'
    | '/admin/news'
    | '/admin/roles'
    | '/admin/news/$id/edit'
    | '/admin/users/admins'
    | '/admin/users/clients'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/_admin'
    | '/admin/init'
    | '/admin/login'
    | '/news/$slug'
    | '/news/'
    | '/admin/_admin/'
    | '/admin/_admin/news/create'
    | '/admin/_admin/config/'
    | '/admin/_admin/dicts/'
    | '/admin/_admin/files/'
    | '/admin/_admin/logs/'
    | '/admin/_admin/news/'
    | '/admin/_admin/roles/'
    | '/admin/_admin/news/$id/edit'
    | '/admin/_admin/users/admins/'
    | '/admin/_admin/users/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/init': {
      id: '/admin/init'
      path: '/init'
      fullPath: '/admin/init'
      preLoaderRoute: typeof AdminInitRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/roles/': {
      id: '/admin/_admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AdminAdminRolesIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/news/': {
      id: '/admin/_admin/news/'
      path: '/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminAdminNewsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/logs/': {
      id: '/admin/_admin/logs/'
      path: '/logs'
      fullPath: '/admin/logs/'
      preLoaderRoute: typeof AdminAdminLogsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/files/': {
      id: '/admin/_admin/files/'
      path: '/files'
      fullPath: '/admin/files/'
      preLoaderRoute: typeof AdminAdminFilesIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/dicts/': {
      id: '/admin/_admin/dicts/'
      path: '/dicts'
      fullPath: '/admin/dicts/'
      preLoaderRoute: typeof AdminAdminDictsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/config/': {
      id: '/admin/_admin/config/'
      path: '/config'
      fullPath: '/admin/config/'
      preLoaderRoute: typeof AdminAdminConfigIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/news/create': {
      id: '/admin/_admin/news/create'
      path: '/news/create'
      fullPath: '/admin/news/create'
      preLoaderRoute: typeof AdminAdminNewsCreateRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/users/clients/': {
      id: '/admin/_admin/users/clients/'
      path: '/users/clients'
      fullPath: '/admin/users/clients/'
      preLoaderRoute: typeof AdminAdminUsersClientsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/users/admins/': {
      id: '/admin/_admin/users/admins/'
      path: '/users/admins'
      fullPath: '/admin/users/admins/'
      preLoaderRoute: typeof AdminAdminUsersAdminsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/news/$id/edit': {
      id: '/admin/_admin/news/$id/edit'
      path: '/news/$id/edit'
      fullPath: '/admin/news/$id/edit'
      preLoaderRoute: typeof AdminAdminNewsIdEditRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminNewsCreateRoute: typeof AdminAdminNewsCreateRoute
  AdminAdminConfigIndexRoute: typeof AdminAdminConfigIndexRoute
  AdminAdminDictsIndexRoute: typeof AdminAdminDictsIndexRoute
  AdminAdminFilesIndexRoute: typeof AdminAdminFilesIndexRoute
  AdminAdminLogsIndexRoute: typeof AdminAdminLogsIndexRoute
  AdminAdminNewsIndexRoute: typeof AdminAdminNewsIndexRoute
  AdminAdminRolesIndexRoute: typeof AdminAdminRolesIndexRoute
  AdminAdminNewsIdEditRoute: typeof AdminAdminNewsIdEditRoute
  AdminAdminUsersAdminsIndexRoute: typeof AdminAdminUsersAdminsIndexRoute
  AdminAdminUsersClientsIndexRoute: typeof AdminAdminUsersClientsIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminNewsCreateRoute: AdminAdminNewsCreateRoute,
  AdminAdminConfigIndexRoute: AdminAdminConfigIndexRoute,
  AdminAdminDictsIndexRoute: AdminAdminDictsIndexRoute,
  AdminAdminFilesIndexRoute: AdminAdminFilesIndexRoute,
  AdminAdminLogsIndexRoute: AdminAdminLogsIndexRoute,
  AdminAdminNewsIndexRoute: AdminAdminNewsIndexRoute,
  AdminAdminRolesIndexRoute: AdminAdminRolesIndexRoute,
  AdminAdminNewsIdEditRoute: AdminAdminNewsIdEditRoute,
  AdminAdminUsersAdminsIndexRoute: AdminAdminUsersAdminsIndexRoute,
  AdminAdminUsersClientsIndexRoute: AdminAdminUsersClientsIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AdminInitRoute: typeof AdminInitRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AdminInitRoute: AdminInitRoute,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
